.travis.yml, auditwheel/condatools.py, auditwheel/elfutils.py, auditwheel/lddtree.py, auditwheel/main_addtag.py, auditwheel/main_lddtree.py, auditwheel/main_repair.py, auditwheel/policy/__init__.py, auditwheel/policy/external_references.py, auditwheel/policy/versioned_symbols.py, auditwheel/tools.py, auditwheel/wheel_abi.py, auditwheel/wheeltools.py, tests/test-wheelhouses.sh
This fixes a bug where `auditwheel lddtree` crashed because of a typo (wrong function name). Then, I added more type information for mypy, and ran the whole thing through yapf.
=> Fix small bug, improve mypy, and run through yapf.

auditwheel/elfutils.py, auditwheel/main.py, auditwheel/policy/external_references.py, auditwheel/repair.py
=> Add RPATH onto libraries that are grafted in

README.rst
=> Update README.rst inline example

tests/test_manylinux.py
I got bitten running the tests on an old manylinux1 cached docker image on my local machine. I don't think travis is impacted.
=> FIX make sure to run the tests with the latest docker images

.travis.yml
Alternative PR to #86, per my suggestion. Happy to close in favour of that PR, just thought I'd throw this out there.
=> Make failing wheelhouse test optional for now

auditwheel/policy/external_references.py
The recursive implementation of get_req_external would fail when two
libraries are linked against each each other, e.g. libfreetype.so.6 and
libharfbuzz.so.0 on Arch Linux.
=> Nonrecursive get_req_external.

auditwheel/policy/__init__.py
for arch detection, e.g. macOS, PyPy, etc..
See:
https://travis-ci.org/ofek/coincurve/jobs/400123068#L1341
https://github.com/peterjc/backports.lzma/commit/21ae77fab139eaafa091e979351b2f6cf580e4f8
cc @njsmith
=> Support more platforms and Python implementations

.travis.yml, tox.ini
In response to: https://github.com/pypa/auditwheel/issues/111
=> Drop the dot when invoking pytest

.travis.yml
Disable broken auto-deployments, disable broken caching
Hoping this will fix the current build flakiness I'm seeing on 3.4 and 3.5.
=> Fix some issues with Travis

README.rst
This PR fixes typos in the README file.
=> Fix typo in README file

tests/unit/test_hashfile.py
=> test: Add unit test for hashfile

tests/unit/test_main.py
=> Add unit tests for `main.py`

.travis.yml, auditwheel/repair.py, auditwheel/tools.py, auditwheel/wheel_abi.py, tests/travis.sh
The linter was already added to tox but was not run on CI builds.
=>  Run linter on CI builds

CHANGELOG.md
Preparing the new release: #181.
=> Add CHANGELOG.md entry for 2.1

CHANGELOG.md
Relates to #198 
@pypa/manylinux, I'll make the release once this PR is approved and merged without waiting for #192
=> Add CHANGELOG.md entry for 2.1.1

.travis.yml
manylinux2014_ppc64le is now available, let's test it.
=> Add tests on ppc64le platform

.travis.yml
manylinux2014_s390x is now available, let's test it.
=> Add tests on s390x platform

CHANGELOG.md
=> Update CHANGELOG.md for 3.0.0 release

.travis.yml, tests/integration/test_manylinux.py
Update test scripts to reflect that.
=> manylinux2014 now uses devtoolset-9

tests/integration/test_manylinux.py, tests/integration/testdependencies/dependency.c, tests/integration/testdependencies/setup.py, tests/integration/testdependencies/testdependencies.c
Draft PR while tracking the progress of `pip` and `manylinux` images.
Use custom `manylinux` images for now.
Use custom `pip` for now
=> Add manylinux_2_24 tests

auditwheel/policy/policy.json
=> Add libexpat.so.1 to whitelisted libraries starting with manylinux2010

src/auditwheel/musllinux.py, tests/unit/test_musllinux.py
=> Simplify musl platform check 

src/auditwheel/main_repair.py, tests/integration/test_bundled_wheels.py
=> Allow `auditwheel repair` to process multiple wheels

src/auditwheel/policy/manylinux-policy.json
Policies extracted from https://github.com/mayeut/pep600_compliance
fix #388
=> feat: add manylinux_2_34 & manylinux_2_35 policies

.github/workflows/test.yml, .pre-commit-config.yaml, noxfile.py, pyproject.toml, src/auditwheel/elfutils.py, src/auditwheel/lddtree.py, src/auditwheel/patcher.py, src/auditwheel/policy/__init__.py, src/auditwheel/policy/external_references.py, src/auditwheel/policy/versioned_symbols.py, src/auditwheel/repair.py, src/auditwheel/wheel_abi.py, tests/integration/test_manylinux.py
Workflows are currently failing because of:
- `pre-commit` configuration
- wrong `gcc-toolset` used on `manylinux_2_28`
This PR updates both.
=> Fix CI workflows

.github/workflows/test.yml, .travis.yml, noxfile.py
codecov has been removed from PyPI: https://about.codecov.io/blog/message-regarding-the-pypi-package/
=> chore: remove pypi codecov usage

src/auditwheel/policy/__init__.py, tests/integration/test_bundled_wheels.py, tests/unit/test_policy.py
follow-up on https://github.com/pypa/auditwheel/pull/466#discussion_r1421374461
=> Allow initializing WheelPolicies with a specific libc & architecture

src/auditwheel/policy/__init__.py, src/auditwheel/policy/musllinux-policy.json
=> feat: add musllinux riscv64 support

src/auditwheel/policy/manylinux-policy.json
Use latest update from https://github.com/mayeut/pep600_compliance
=> fix: manylinux_2_37 & manylinux_2_38 policies

.pre-commit-config.yaml, pyproject.toml, src/auditwheel/architecture.py, src/auditwheel/condatools.py, src/auditwheel/elfutils.py, src/auditwheel/lddtree.py, src/auditwheel/main.py, src/auditwheel/main_lddtree.py, src/auditwheel/main_repair.py, src/auditwheel/main_show.py, src/auditwheel/policy/__init__.py, src/auditwheel/repair.py, src/auditwheel/tools.py, src/auditwheel/wheel_abi.py, src/auditwheel/wheeltools.py, tests/integration/test_manylinux.py, tests/unit/test_elfutils.py, tests/unit/test_musllinux.py, tests/unit/test_policy.py
This uncovered a few issues so might as well add some more checks.
=> chore: better typing hints

setup.py
`patchelf` is now a pypi package.
=> Correct `patchelf` dependency

src/auditwheel/tmpdirs.py, tests/unit/test_wheeltools.py
=> fix: resolve path of InTemporaryDirectory name

src/auditwheel/repair.py, src/auditwheel/wheeltools.py
=> fix: logged repaired file path
