.travis.yml
auditwheel/lddtree.py
auditwheel/main_show.py
auditwheel/repair.py
test-requirements.txt

@njsmith: I think this might fix the issue on your platform with pyside (?). The linker searches RPATH, then LD_LIBRARY_PATH, then RUNPATH, but for the purpose of determining what libs to copy into the wheel, as you pointed out by email, it makes more sense to search RUNPATH first.

Put RUNPATH before LD_LIBRARY_PATH

---

.travis.yml
README.rst

Fixes #10. After a new release to PyPI, the links there (pulled from README) should be updated as well.

Fix links in README.rst to new pypa/ locations

---

auditwheel/policy/versioned_symbols.py

The method `max_versioned_symbol` below crashes when the symbol has an underscore in the name, for example `HDF5_SERIAL_1.8.13`.

fix max versioned symbol

---

auditwheel/main_addtag.py
auditwheel/main_repair.py
auditwheel/policy/__init__.py
auditwheel/repair.py
auditwheel/wheeltools.py
tox.ini

This is a fix for #19. auditwheel repair now automatically update the filename and `WHEEL`'s 'Tag' entry to remove the old `linux` platform tags and replace them with the matching `manylinux1` tags to make the wheel suitable for upload to PyPI.
Here is an example run on a numpy wheel built using the manylinux docker image and @matthew-brett's ATLAS rpms:
```
Repairing numpy-1.10.4-cp35-cp35m-linux_x86_64.whl
Grafting: /usr/lib64/atlas/libtatlas.so.3.10
Grafting: /usr/lib64/libgfortran.so.3.0.0
Setting RPATH: numpy/linalg/_umath_linalg.cpython-35m-x86_64-linux-gnu.so to "$ORIGIN/../.libs"
Setting RPATH: numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so to "$ORIGIN/../.libs"
Setting RPATH: numpy/linalg/lapack_lite.cpython-35m-x86_64-linux-gnu.so to "$ORIGIN/../.libs"
Previous filename …
```

[MRG] Update the wheel tags when repairing

---

.travis.yml
tests/test_manylinux.py

This uses 2 docker containers, one to build numpy and repair the wheel to make it manylinux1 compatible and the other to quickly check that numpy can be installed and works.

Integration test for auditwheel repair

---

auditwheel/policy/__init__.py

When repairing Python wheel on 32 bits linux, the resulting wheel file ends suffixed in a wrong way : 'manylinux1__i686' instead of 'manylinux1_i686'. The problem comes from the get_arch_name in the policy sub module, looks like a typo to me.

fix invalid manylinux wheel filename for 32 bits platform

---

auditwheel/repair.py

Maybe needs a test for namespace packages?
Not necessarily volunteering - if it isn't immediately necessary I'd rather just continue on my merry way. :stuck_out_tongue_closed_eyes:

Remove __init__.py check

---

auditwheel/elfutils.py
auditwheel/lddtree.py
auditwheel/repair.py
requirements.txt
test-requirements.txt
tests/test_bundled_cffi.py

In that version symbol and section names are strings, not bytes, fixes #49.
Also some cosmetic changes - added required test dependencies and fixed typo in error message relating patchelf version.

support pyelftools-0.24

---

auditwheel/policy/versioned_symbols.py
tests/test_policy.py

policy_is_satisfied always returned True.
show output before:
```
The wheel references external versioned symbols in these system-
provided shared libraries: libQt5Gui.so.5 with versions {'Qt_5'},
libQt5PrintSupport.so.5 with versions {'Qt_5'}, libc.so.6 with
versions {'GLIBC_2.2.5', 'GLIBC_2.3', 'GLIBC_2.4', 'GLIBC_2.3.4',
'GLIBC_2.14'}, libstdc++.so.6 with versions {'GLIBCXX_3.4.21',
'CXXABI_1.3', 'GLIBCXX_3.4.20', 'GLIBCXX_3.4'}, libm.so.6 with
versions {'GLIBC_2.2.5'}, libgcc_s.so.1 with versions {'GCC_3.0'},
libQt5Core.so.5 with versions {'Qt_5.7', 'Qt_5'}, libQt5Widgets.so.5
with versions {'Qt_5'}
The following external shared libraries are required by the wheel:
```
show output after:
```
DEBUG:auditwheel.policy.versioned_symbols:Package requires GLIBCXX_3.4.20, incompatible with …
```

Fix versioned symbol policy check

---

auditwheel/wheel_abi.py

That PR is there to adress issue #32. No binaries should be found in the purelib folder of a wheel. So raise an error if it is the case.

check for invalid binary wheel

---

auditwheel/policy/versioned_symbols.py

`set(dict.keys())` is the same as `set(dict)`. This shortens the line and lets us remove linewrapping

Simplify code slightly

---

auditwheel/policy/__init__.py
auditwheel/policy/versioned_symbols.py
tests/test_policy.py

Fixes #72. I'm unsure if this test is useful so let me know if I should be doing something different.

support versioned symbols with more underscores

---

auditwheel/policy/policy.json

Added libresolv to the whitelisted libraries

---

auditwheel/wheeltools.py

https://github.com/pypa/auditwheel/issues/47
This skips pure wheels that don't need a platform added. @rmcgibbo 
My package was getting errors because Click is a pure wheel. This fixed my issue.

Skip pure wheels

---

auditwheel/wheel_abi.py
tests/test_manylinux.py
tests/testpackage/setup.py
tests/testpackage/testpackage/__init__.py
tests/testpackage/testpackage/testprogram.c

This makes it possible to relocate and distribute executable binaries as well as Python extension binaries.
We would like to use this feature in the [LALSuite](https://pypi.org/project/lalsuite/) package. See https://git.ligo.org/lscsoft/lalsuite/merge_requests/164.

Process non-Python binaries (e.g. binary executables)

---

.travis.yml

This is preventing automatic deployments to PyPI building on tags,
as the branches.only = [master] causes all tag builds to be ignored.
See note[*]: "Note that safelisting also prevents tagged commits from
being built."
[*]: https://docs.travis-ci.com/user/customizing-the-build#Safelisting-or-blocklisting-branches

Remove "branches" stanza from Travis build

---

.travis.yml
requirements.txt
tests/travis.sh

Ensure Travis fails when tests fail [ignore CI failure]

---

auditwheel/lddtree.py
auditwheel/main_addtag.py
auditwheel/main_show.py
auditwheel/policy/external_references.py
auditwheel/policy/versioned_symbols.py
auditwheel/tools.py
auditwheel/wheel_abi.py
tests/test_pyfpe.py

It overlaps with #116 but this just removes unused imports.

Removed unused imports in different files

---

tests/test_manylinux.py

There's now an official image and pip supports manylinux2010, so these workarounds should be unnecessary.

Update tests for manylinux2010

---

auditwheel/elfutils.py
auditwheel/hashfile.py
auditwheel/lddtree.py
auditwheel/main.py
auditwheel/main_addtag.py
auditwheel/main_lddtree.py
auditwheel/main_repair.py
auditwheel/main_show.py
auditwheel/policy/__init__.py
auditwheel/policy/external_references.py
auditwheel/policy/versioned_symbols.py
auditwheel/repair.py
auditwheel/tools.py
auditwheel/wheel_abi.py
test-requirements.txt
tox.ini

This adds `flake8` to `tox` to lint the code base and fixes the current lint errors to make the tests pass.
Closes: #115

Run linter in test suite

---

auditwheel/genericpkgctx.py

Instead of raising an empty ValueError when encountering an unknown file format, provide a meaningful error message in the exception. This should make it easier for users to tell what went wrong.

Improve error message on invalid package

---

pyproject.toml
requirements.txt
tests/test_manylinux.py

Make setuptools a build dependency in pyproject.toml and set it as the
build backend.

Use pyproject.toml

---

auditwheel/main.py
auditwheel/policy/__init__.py

At the moment the platform check is done when the policy module gets
imported. This makes it difficult to run the test suite on non-Linux
platforms. Moving the check to the CLI entry point allows the tests to
run and retains the current behavior and exits on non-Linux platforms
when running the tool.
Note that in a previous commit I accidentally commented out the check,
that's why it's shown commented in this diff.
Closes: #154

Make it possible to run the test suite on non-Linux systems

---

requirements.txt

This the backport library needed for pre-3.5 interpreters only. Since we
only support 3.5 and later, it can be removed.

Remove typing from requirements.txt

---

auditwheel/wheel_abi.py
test-requirements.txt
tests/unit/test_wheel_abi.py

Instead of just outputting the first shared library found in `purelib`, include a list of all offending files.

Show all shared libraries found in purelib

---

test-requirements.txt
tests/integration/test_manylinux.py

The integration tests previously had a single big `docker_container` fixture which actually started 2 docker containers. This breaks it up into separate fixtures, which simplifies things a bit, and allows tests to use one container without starting the other (one test already does so).
It also switches from constructing `docker` commands to run in a subprocess to using the docker Python API.

Break up docker test fixtures

---

tox.ini

This pull request adds ability to specify options passed to underlying ``pytest`` command when running ``tox``.

Add ability to pass options to pytest in tox.ini

---

auditwheel/repair.py
test-requirements.txt
tests/integration/test_manylinux.py
tests/integration/testrpath/MANIFEST.in
tests/integration/testrpath/a/a.c
tests/integration/testrpath/a/a.h
tests/integration/testrpath/b/b.c
tests/integration/testrpath/b/b.h
tests/integration/testrpath/setup.py
tests/integration/testrpath/src/testrpath/testrpath.c
tox.ini

If collected library has ``RPATH`` or ``RUNPATH`` set now ``auditwheel`` changes it to a new location of all collected libraries.
This patch is extracted from #133 to make that pull request focused on only one thing.

Always change rpath of grafted libraries

---

auditwheel/wheel_abi.py

```
auditwheel/wheel_abi.py:23: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import defaultdict, Mapping, namedtuple
```

Fix deprecation warning

---

auditwheel/repair.py
tests/integration/test_manylinux.py
tests/integration/testrpath/setup.py

Due to bug in patchelf https://github.com/NixOS/patchelf/issues/94 if shared object has DT_RUNPATH attribute it is not replaced with DT_RPATH if --force-rpath is given, so one must clear all rpath attributes before setting new.
This pull request closes #29.
Also this pull request is resubmit of #133 because old showed too much changed files and it is easier for me to resubmit.

Clear rpath before setting

---

auditwheel/tmpdirs.py
tests/unit/test_tmpdirs.py

TemporaryDirectory class was for python 2 compatibility.
Using the python 3 provided TemporaryDirectory should be safest.
This PR also adds unit tests covering `tmpdirs.py`

 Use python provided TemporaryDirectory

---

.coveragerc
.travis.yml
tests/integration/test_manylinux.py
tests/travis.sh

Try to collect code coverage information & report it through codecov. This is what the results look like: https://codecov.io/gh/pypa/auditwheel/branch/codecov
I think this is only reporting coverage from the unit tests at the moment. I'd like to try to figure out including coverage from the integration tests which run auditwheel inside docker containers, but that will probably be a bit more involved.
I did have to switch to an editable install in Travis. It seems awkward to match up the executed code with the source files otherwise.

WIP: Codecov integration

---

.travis.yml
README.rst
tests/integration/test_manylinux.py

(Hopefully)
I noticed that all the tests which use docker repeat trying to pull the same images and do the same setup steps inside the containers. So this adds a layer of fixtures to create temporary docker images in session-scoped fixtures, deleting them when tests finish.
On my system, this makes the tests finish in under half the time they previously took (~800 seconds to ~320 seconds). It should also mean that all the docker based tests run in a consistent environment, even if an image is updated or a package released while the tests are running.
I've also told Travis to cache the wheels built in the tests. That won't affect the test time on this PR, because there's nothing cached yet, but once it's merged it should avoid the need to recompile numpy each time.

Make integration tests faster

---

tests/unit/test_policy.py

Remove duplicate policies in the unit test to avoid having to make
changes in both the actual implementation and the test as well.

test: Simplify policy unit test

---

auditwheel/main.py

found using [asottile/python3.10](https://github.com/asottile/python3.10)
```console
$ .tox/py310/bin/auditwheel --version
auditwheel 2.1.1.dev2 installed at /tmp/x/repos/pypa/auditwheel (python 3.1)
```
```console
$ .tox/py310/bin/auditwheel --version
auditwheel 2.1.1.dev2 installed at /tmp/x/repos/pypa/auditwheel (python 3.10)
```

Fix --version for python 3.10

---

tests/pr134/hello_module/.gitignore
tests/pr134/hello_module/README.md
tests/pr134/hello_module/extensions/.gitignore
tests/pr134/hello_module/extensions/testzlib.cpp
tests/pr134/hello_module/extensions/testzlib.h
tests/pr134/hello_module/extensions/testzlib.sh
tests/pr134/hello_module/hello.cpp
tests/pr134/hello_module/hello/__init__.py
tests/pr134/hello_module/setup.py
tests/pr134/hello_module/tests/manual_test.py
tests/test_hello.py

UPDATE: This PR was modified to only include the test cases that @ehashman has requested.
Hi,
Our wheel has a complicated dependency structure. But the gist of it is the following:
dbcore.so (py_ext) -> lib_tl.so (non-py_ext) -> libcurl.so (external library to be grafted)
Because lib_tl is a non-py extension of dbcore, it was not added to the `full_external_refs` dictionary, which is used by `repair.py` to patch the sonames. So the final result is that lib_tl was not patched, and the package was broken.
- Change 1: I added this case to the `full_external_refs` dictionary.
In addition, dbcore already had an `RPATH` set to `$ORIGIN`. So because of its dependency to libcurl.so, `patchelf_set_rpath` *replaced* it to `$ORIGIN/.libs` in `repair.py`, even though it was not necessary. This way, …

Test cases: Unwanted RPATH overwrite and Failing to patch internal non-py extensions

---

tests/integration/test_manylinux.py

Run integration tests on manylinux using the python version used to test auditwheel.
Since travis-ci is running 3.5, 3.6 & 3.7, we're better off testing those versions inside manylinux containers rather than testing 3 times the exact same thing.

Run manylinux tests using current python version

---

auditwheel/policy/__init__.py
tests/unit/test_policy.py

All unknown machines were detected as `x86_64` or `i686` depending on their word size.
Update the detection in order to get the untouched machine name for those arch and only consider i686 running on x86_64 to be eligible to a name change.
Example:
before, `aarch64` was reported as `x86_64`, now `aarch64`

Update machine detection

---

CHANGELOG.md

relates to #205 
@di, I think I'll do a release candidate as a first step. That should allow the manylinux2014 image to be released and tested before releasing 3.0.0 a bit later.

Add CHANGELOG.md entry for 3.0.0rc1

---

.travis.yml
test-requirements.txt
tests/integration/test_bundled_cffi.py
tests/integration/test_bundled_pypy_snappy.py
tests/integration/test_manylinux.py
tests/integration/test_pyfpe.py
tests/integration/testdependencies/dependency.c
tests/integration/testdependencies/testdependencies.c
tests/unit/test_policy.py

Add tests on top of #192
pip built from https://github.com/mayeut/pip/tree/manylinux2014
docker image is automatically built from branch used for pypa/manylinux#348

WIP - manylinux2014 policy tests

---

tox.ini

We already support 3.8 but it was not listed in tox.ini.

Add Python 3.8 to tox.ini

---

tests/integration/test_manylinux.py

As pip 20.0.1 is not able to install the repaired wheel
`testpackage-0.0.1-py3-none-manylinux1_x86_64.whl` due to a bug, we have
to pin to the previous version to unblock the test suite.
We should remove the pin once https://github.com/pypa/pip/issues/7626 is
resolved.
See #219.

test: Pin pip to version 19.3.1 in test_manylinux

---

auditwheel/repair.py
tests/integration/multiple_top_level/MANIFEST.in
tests/integration/multiple_top_level/Makefile
tests/integration/multiple_top_level/lib-src/a/a.c
tests/integration/multiple_top_level/lib-src/a/a.h
tests/integration/multiple_top_level/lib-src/b/b.c
tests/integration/multiple_top_level/lib-src/b/b.h
tests/integration/multiple_top_level/pyproject.toml
tests/integration/multiple_top_level/setup.cfg
tests/integration/multiple_top_level/setup.py
tests/integration/multiple_top_level/src/example_a.pyx
tests/integration/multiple_top_level/src/example_b.pyx
tests/integration/test_manylinux.py

Put libraries in $WHEELNAME.libs

---

tests/integration/conftest.py

This file is used in one of the Dockerized tests. However, pytest
invokes the `import numpy` statement while it is collecting the test
cases on setup. This import can fail if the host environment does not
have numpy installed.

Skip "quick_check_numpy.py" in pytest collection

---

auditwheel/wheeltools.py
requirements.txt

wheel in version 0.34 introduce fix for pypy tags https://github.com/pypa/wheel/issues/328

fixes for auditwheel to depend on wheel 0.34

---

tests/integration/test_manylinux.py

Now that pip 20.0.2 is out we can remove the version pin in the tests.
Related: #219

test: Remove pin for pip

---

auditwheel/main_addtag.py
tests/integration/test_addtag.py

We upgraded to wheel 0.34.1 and the API is slightly different. The
addtag command was not updated for the change.
The included test fails without the fix.

Fix obsolete wheel usage in addtag

---

auditwheel/elfutils.py
auditwheel/policy/external_references.py
tests/integration/testdependencies/dependency.c
tests/integration/testdependencies/setup.py
tests/integration/testdependencies/testdependencies.c
tests/unit/test_elfutils.py

`s390x`/`ppc64le` ELF dynamic linkers do not start with `ld-linux`and therefore, were not excluded from analysis.
Relates to #212 
Fixes https://github.com/pypa/manylinux/issues/412
The tests did not reveal this issue and shall be updated. I don't know how to get this done since all symbols in the linker are private (or seem to be).
@wdirons, @st-pasha, any simple test we could include to reproduce this behavior in tests ?

Always exclude ELF dynamic linker/loader

---

auditwheel/condatools.py
auditwheel/main_repair.py
auditwheel/patcher.py
auditwheel/repair.py
tests/integration/test_manylinux.py
tests/unit/test_elfpatcher.py

This adds the ELF patcher interface from #187 to decouple the patching from the main repair logic and make it easier to add new ELF binary patcher implementations.

Create ELF patcher interface 

---

auditwheel/main_repair.py
auditwheel/repair.py
tests/integration/sample_extension/pyproject.toml
tests/integration/sample_extension/setup.py
tests/integration/sample_extension/src/sample_extension.pyx
tests/integration/test_manylinux.py

Add --strip option to 'repair'

---

.travis.yml
README.rst
auditwheel/policy/__init__.py
auditwheel/repair.py
setup.cfg
tests/integration/internal_rpath/setup.py
tests/integration/test_manylinux.py
tests/unit/test_elfpatcher.py
tests/unit/test_policy.py
tests/unit/test_repair.py
tox.ini

Python 3.5 reached its end-of-life, time to drop support.
Repairing python 3.5 wheels is still supported.

Drop python 3.5 support

---

.travis.yml
setup.cfg
tests/integration/test_manylinux.py
tox.ini

This PR adds python 3.9 tests & advertise python 3.9 support.
I had failures with numpy tests on python 3.9 only thus I bumped the numpy version. This lead to timeouts on arm64 => switch to arm64-graviton2 for aarch64, always running on focal so also changed to focal as default distro. python 3.7 is missing on focal for ppc64le, s390x => use python 3.8 for non amd64 arch.

Add python 3.9 tests & advertise python 3.9 support

---

auditwheel/tools.py

Clean-up code base a bit by removing unused `find_package_dirs` function

Remove unused `find_package_dirs` function

---

auditwheel/condatools.py
auditwheel/wheeltools.py

Those helpers are only helpful for python 2/3 compatibility, they're not necessary as `auditwheel` has been python 3 only since its 1st version.

Remove usage of `wheel` imported helpers for python 2/3 compatibility

---

auditwheel/wheeltools.py

base64 encoding in `wheel.utils` strips `=` padding. the same shalle be done.

Fix base64 encoding

---

auditwheel/condatools.py
auditwheel/lddtree.py
auditwheel/main_show.py
auditwheel/repair.py
auditwheel/tmpdirs.py
auditwheel/wheeltools.py

There were some things left from previous manual updates, use of `pyupgrade --py36-plus` found those:
- Do not specify `mode=rt` for `open` as it is the default
- Use `OSError` instead of `IOError`
- Modernize class syntax
- Convert some string formatting in f-strings

Modernize Python syntax using `pyupgrade --py36-plus`

---

.github/workflows/lint.yml
.github/workflows/test.yml
.travis.yml
auditwheel/condatools.py
auditwheel/elfutils.py
auditwheel/genericpkgctx.py
auditwheel/hashfile.py
auditwheel/lddtree.py
auditwheel/main.py
auditwheel/main_addtag.py
auditwheel/main_lddtree.py
auditwheel/main_show.py
auditwheel/patcher.py
auditwheel/policy/__init__.py
auditwheel/policy/external_references.py
auditwheel/policy/versioned_symbols.py
auditwheel/repair.py
auditwheel/tmpdirs.py
auditwheel/tools.py
auditwheel/wheel_abi.py
auditwheel/wheeltools.py
setup.cfg
tests/install.sh
tests/travis.sh

Move to GHA in order to save some travis-ci credits on the pypa account.
xref pypa/packaging#395, pypa/manylinux#988

Use GitHub Actions for x86_64 tests

---

auditwheel/main_repair.py
tests/integration/test_manylinux.py

Always repair as a single wheel.
Add argument `--only-plat` to `auditwheel repair` for those who were keeping only the lowest priority tag wheel (i.e. the one requested by `--plat` argument).
fixes #281, closes #284 
builds on top of #288

Always repair as a single wheel

---

.travis.yml

ppc64le test is flaky at the moment on travis-ci, let's allow failures for now.
see pypa/auditwheel#292

Allow failures on ppc64le

---

tests/integration/test_manylinux.py

With multiple manylinux images, it's not always easy to guess what the repaired wheel will be compatible with.
Add a helper for the auditwheel show check that allows to relax the constraint on the expected policy as long as it's compatible with the expected one.
The `strict` argument of the helper allows to choose wether the check shall be relaxed or not.

Rework auditwheel show checks in test_manylinux.py

---

auditwheel/wheel_abi.py
tests/integration/nonpy_rpath/README.md
tests/integration/nonpy_rpath/extensions/testcrypt.cpp
tests/integration/nonpy_rpath/extensions/testcrypt.h
tests/integration/nonpy_rpath/nonpy_rpath.cpp
tests/integration/nonpy_rpath/nonpy_rpath/__init__.py
tests/integration/nonpy_rpath/setup.py
tests/integration/test_manylinux.py

This PR resolves #136, and replaces the open (stalled) PR #139 from @thomaslima (closes #139) and rebase/rework the open PR #283 from @bdice (closes #283)
Summary in #283 is the nice one, so go there for more information.
Tests are much simpler here and still reproduce the issue without the fix of course.
Thanks @bdice, @thomaslima

Fix: Patch RPATHs of non-Python extension dependencies

---

auditwheel/main_repair.py

e.g.
```
Legacy tags are still supported and alias the new PEP600 tags:
- manylinux1_x86_64 is an alias for manylinux_2_5_x86_64
- manylinux2010_x86_64 is an alias for manylinux_2_12_x86_64
- manylinux2014_x86_64 is an alias for manylinux_2_17_x86_64
```
Full output for now is:
```
usage: auditwheel repair [-h]
[--plat {linux_x86_64,manylinux_2_5_x86_64,manylinux_2_12_x86_64,manylinux_2_17_x86_64,manylinux_2_24_x86_64,manylinux1_x86_64,manylinux2010_x86_64,manylinux2014_x86_64}]
[-L LIB_SDIR] [-w WHEEL_DIR] [--no-update-tags]
[--strip] [--only-plat]
WHEEL_FILE
Vendor in external shared library dependencies of a wheel.
positional arguments:
WHEEL_FILE            Path to wheel file.
optional arguments:
-h, --help            show this help message and exit
--plat …
```

Inform about aliases in `auditwheel repair --help`

---

README.rst

Adds [PEP 600](https://www.python.org/dev/peps/pep-0600/) to the list of Linux wheels and to the list of platform tags that are supported (addressing #302). The description as `manylinux_x_y` is based on the wording in the file `README.rst` of the manylinux project: https://github.com/pypa/manylinux/blob/f395ab8f7c5226e1d8557691a843fefad634c4f6/README.rst#manylinux.

DOC: mention PEP 600 in `README.rst`

---

auditwheel/main.py
requirements.txt

The only reason we needed this was to look at the version metadata and
the installation location. We can do this with `importlib.metadata`
which is part of Python since 3.8 and is significantly faster to import
than `pkg_resources`.
Closes: #306

Remove dependency on `pkg_resources`

---

README.rst
tests/integration/test_manylinux.py

This should speed-up the tests a bit.

Use python slim images to run tests

---

tox.ini

Tox already does that by default.
In Fedora, when we build RPM packages,
we use a tox plugin that installs the test requirements from RPMs.
It does not know how to install the package we are building.

Don't installs self in tox deps

---

auditwheel/error.py
auditwheel/lddtree.py
auditwheel/libc.py
auditwheel/musllinux.py
auditwheel/policy/__init__.py
auditwheel/policy/musllinux-policy.json
tests/unit/test_musllinux.py

This aims to modify less things than #313 at first to ease the review.
Once there are sufficient tests, the added complexity of #313 might be something to look into as it might be a good step forward to cross-repairing/cross-checking wheels.
@lkollar, thanks for the work in #313 (and in manylinux). What do you think of doing this in 2 steps as mentioned above?
1. add support for musllinux without extensively modifying the code base for manylinux
2. once we can test everything properly, refactor policy loading/management

Add support for musllinux

---

setup.cfg

Fix setuptools warnings seen during builds (deprecation notices)

fix: build warnings

---

MANIFEST.in

Add exclusion for files that are not needed for the SDist

fix: SDist includes files it shouldn't include

---

tests/integration/internal_rpath/Makefile
tests/integration/multiple_top_level/Makefile
tests/integration/nonpy_rpath/extensions/testcrypt.cpp
tests/integration/test_manylinux.py
tests/integration/testrpath/setup.py

Add musllinux integration tests for #315 integration tests now that upstream musllinux images are here.

Add musllinux integration tests

---

tests/integration/test_manylinux.py

pip is now building in-place leaving some files around which make some tests to fail when building a second time for musllinux.

fix: clean before build in test_manylinux

---

src/auditwheel/tools.py
src/auditwheel/wheeltools.py
tests/integration/test_bundled_wheels.py

Setting `SOURCE_DATE_EPOCH` in the environment will set the time stamps
of all files and directories in the produced wheels to the specified
value.
Closes: #346

Add support for SOURCE_DATE_EPOCH

---

README.rst

Subj, from the readme it's not obvious that a separate non-automatically installed dependency is required, so I think we need to update the text.

Reflect dependency on patchelf in README

---

noxfile.py
pyproject.toml
requirements.txt
setup.cfg
setup.py
test-requirements.txt

I verified manually that the SDist/wheel diff are only the expected ones.

chore: move from `pbr` to `setuptools_scm`

---

noxfile.py

Allows to setup a development environment with `nox -s develop-3.6`.
Requires #358

chore: add `nox` develop session

---

MANIFEST.in

setuptools_scm includes some files by default that are not included when building from a github archive. Include them manually to produce the same build.
Fixes #321

fix: building from a github archive fails

---

MANIFEST.in

Required for downstream packagers.
Reported in #321 
Tests were removed from SDist in 5.1.0

fix: include tests in SDist

---

src/auditwheel/tools.py
tests/unit/test_tools.py

fix: files are not compressed with ZIP_DEFLATED

---

.github/workflows/test.yml

cancel in progress PR builds if there's a new commit on the PR to free up CI resources.

ci: use GHA concurrency group

---

CHANGELOG.md

At https://github.com/pypa/auditwheel/blob/main/CHANGELOG.md#320, the links within "User-facing changes" are incorrectly formatted.
For example, the first one should be a link to `https://github.com/pypa/auditwheel/pull/237`, displaying simply as `#237`, but instead it's the opposite - a link to `#237` displaying as `https://github.com/pypa/auditwheel/pull/237`

Corrected link syntax

---

tests/integration/test_manylinux.py

The volume bound to the manylinux/musllinux for `/auditwheel_src` uses the host uid for file ownership which is different from the uid used inside the containers.
git now checks uid to allow/deny actions.
This adds `/auditwheel_src` to git safe directories to allow setuptools_scm to infer auditwheel version inside the containers.

fix: add `/auditwheel_src` to git safe directories

---

src/auditwheel/patcher.py
src/auditwheel/repair.py
tests/unit/test_elfpatcher.py

This changes `auditwheel repair` to use the multiple-occurrences invocation of `patchelf --replace-needed` (i.e. `patchelf --replace-needed old_1.so new_1.so --replace-needed old_2.so new_2.so filename.so`) instead of calling `patchelf` multiple times. I observed ~~two~~ three benefits to this:
1. Each call to `patchelf` seems to increase the size of the resulting binary. Though in my instance the compressed size was comparable, the inflated size difference was significant (see below for a comparison). This is meaningful when wheels are distributed installed e.g. as part of a Docker image.
2. Reducing the number of calls to `patchelf` also seems to result in faster wheel repair.
3. Without this change, `auditwheel repair --strip ...` would produce a broken wheel that gave an `ELF load …

Update 'replace_needed' to reduce total calls to 'patchelf'

---

tests/integration/test_glibcxx_3_4_25/setup.py
tests/integration/test_glibcxx_3_4_25/testentropy.cpp
tests/integration/test_manylinux.py
tests/integration/testdependencies/dependency.c
tests/integration/testdependencies/testdependencies.c

draft just to see if we're seeing complaints with `GLIBCXX_3.4.25` symbol version.

test: add manylinux_2_28 tests

---

.pre-commit-config.yaml

Update all hooks to versions still supporting python 3.6
I've not yet looked at what quirks we might run into if updating to run with python 3.7 targeting python 3.6 code (& did not discuss the possibility to drop 3.6 altogether for the code base)

chore(deps): update pre-commit hooks

---

pyproject.toml
src/auditwheel/main_addtag.py
src/auditwheel/main_repair.py
src/auditwheel/main_show.py
src/auditwheel/wheel_abi.py

The current log message in case a wheel file contains no compiled extension is not very clear regarding that's the issue is.
I've tried to add a clarification that I how will make it clearer for uses to understand what when wrong
(I opened https://github.com/pypa/cibuildwheel/issues/1247 since it was not clear to me that the error meant, I though it was complaining about the file name abi identifier or something similar)

Improve log message in case of NonPlatformWheel error

---

src/auditwheel/main_repair.py
src/auditwheel/repair.py
tests/integration/test_bundled_wheels.py
tests/integration/test_manylinux.py

This is a follow-up of #310 by @rossant, only keeping the `exclude` option as suggested by @mayeut
Closes #76
Closes #241
Closes #310
Fixes #391
Original PR description:
----
This is a quick fix to solve an issue I have with my project and for which auditwheel seemed to help. I don't know if this approach is suitable to other users of auditwheel.
I develop a C graphics library ([datoviz](https://github.com/datoviz/datoviz/)) that depends on Vulkan and comes with Cython bindings. https://github.com/datoviz/datoviz/issues/13 for Linux (at least Ubuntu 20.04, that would be a start).
1. As a first step, I compile the C project and get a libdatoviz.so shared library.
2. Then, I build the Cython library, which has a dynamic dependency to libdatoviz.
3. I'd like to bundle both the Cython …

Add --exclude option to auditwheel repair

---

src/auditwheel/patcher.py
tests/unit/test_elfpatcher.py

chore: bump required patchelf version to 0.14

---

src/auditwheel/policy/__init__.py
tests/unit/test_policy.py

Towards https://github.com/pypa/manylinux/pull/1455

Use armv7l policy for 64-bit arm kernel in 32-bit mode (armv8l)

---

tests/integration/test_manylinux.py

Support for manylinux_2_24 has ended on January 1st, 2023.
The mirrors for debian stretch (base image) have moved & require reconfiguration if tests are to be kept.
Given the manylinux image is EOL, just drop the tests.

chore(tests): remove manylinux_2_24 tests

---

src/auditwheel/policy/external_references.py
tests/unit/test_policy.py

* Fixed regex for filtering >1 digit for X and Y in libpythonXY
* I doubt Python 10 is coming anytime soon, but it would work now! 
* Added tests for `filter_libs` in `lddtree_external_references`
Fixes #418.

Filter libpythonXY for greater than single digits

---

src/auditwheel/main_show.py
src/auditwheel/repair.py

Since Python 3.7 the insertion order to `dict` has been preserved, thus OrderedDict is no longer necessary.
Note that `src/auditwheel/_vendor/wheel/wheelfile.py` uses OrderedDict, but is not modified. This was modified upstream from https://github.com/pypa/wheel/pull/561

Remove OrderedDict

---

src/auditwheel/patcher.py
tests/unit/test_elfpatcher.py

Python 3.12 removed the `distutils` module from stdlib.
Adherence to this module in auditwheel sources shall be removed.

chore: remove direct usage of distutils

---

tests/integration/test_manylinux.py

Prepare for python 3.12, numpy will require OpenBLAS rather than atlas.
Furthermore, atlas fails randomly on travis-ci on manylinux_2_28 with a `assertion !pthread_create(&thr->thrH, &attr, rout, arg) failed, line 119 of file /builddir/build/BUILD/ATLAS/s390x_base/..//src/threads/ATL_thread_start.c` message so this should take care of that as well.

chore: use openblas on manylinux_2_28

---

.github/workflows/test.yml
noxfile.py
pyproject.toml
setup.cfg
tests/integration/test_manylinux.py

NumPy build has moved to meson and updates to the tests are required for numpy tests to pass.

chore: add python 3.12

---

.github/workflows/test.yml
.pre-commit-config.yaml
README.rst
noxfile.py
pyproject.toml
setup.cfg
src/auditwheel/lddtree.py
src/auditwheel/main.py
src/auditwheel/wheel_abi.py
tests/integration/test_manylinux.py

With #455 going in, the next release will be a major one, we might as well drop python 3.7 (EOL) at the same time.

chore: drop python 3.7

---

src/auditwheel/policy/__init__.py
tests/unit/test_policy.py

fix: bitness detection

---

src/auditwheel/lddtree.py
src/auditwheel/main_repair.py
src/auditwheel/main_show.py
src/auditwheel/repair.py
src/auditwheel/wheel_abi.py
tests/integration/test_bundled_wheels.py
tests/integration/test_manylinux.py
tests/unit/test_wheel_abi.py

When using `--exclude libfoo.so`, dependencies of `libfoo.so` are still being analyzed & grafted.
This commit moves the exclusion analysis to `lddtree` and filters  `libfoo.so` `DT_NEEDED` entries thus excluding its dependencies from the tree.

fix: `--exclude libfoo.so` shall ignore dependencies of `libfoo.so`

---

src/auditwheel/repair.py
tests/integration/test_manylinux.py

As the diff in tests showed, this was the original intent but the tests were not working properly.
close #477  (maintainers can't push to that PR)
> I believe this would address https://github.com/pypa/auditwheel/issues/451.
>
> We use a tool that uses ldd to make sure software packages don't have outside dependencies. After starting to try using auditwheel, .so files under the libs folder are flagged because the RPATH is set to dest_dir, which is not right. Even though it should never have runtime implications (because the RPATH of the first library in the dependency chain is correct), we'd rather fix this upstream rather than having to add explicit allowlisting to our setup.
>
> This fixes that by setting RPATH to $ORIGIN in those cases. I've done some manual testing and that seems to …

fix: replace RPATH on copied libs to the folder where they're copied ($ORIGIN)

---

src/auditwheel/elfutils.py
src/auditwheel/repair.py

As part of [repairwheel](https://github.com/jvolkman/repairwheel), auditwheel is vendored and can patch linux wheels from Windows. These are some of the more innocuous tweaks I've had to make to run successfully in a Windows environment.
Fixes:
- path handling in various places ('\\' vs '/')
- newline when writing the new binary "script" shim

Portability fixes when running on windows

---

src/auditwheel/repair.py
tests/integration/test_manylinux.py

close https://github.com/pypa/auditwheel/issues/488
only create `${package}.libs` when needed

fix: don't create empty .libs directory

---

.github/workflows/test.yml
.pre-commit-config.yaml
.travis.yml
README.rst
noxfile.py
pyproject.toml
setup.cfg
src/auditwheel/elfutils.py
src/auditwheel/policy/__init__.py
src/auditwheel/repair.py
src/auditwheel/tools.py
src/auditwheel/wheeltools.py
tests/integration/test_manylinux.py
tests/integration/testpackage/testpackage/__init__.py

Python 3.8 has reached EOL.
Drop support for Python 3.8 and fix test pipelines.

chore: drop python 3.8

---

src/auditwheel/tools.py
src/auditwheel/wheeltools.py
tests/unit/test_tools.py

Implement a new utility function wrapping `os.walk` with the following modifications:
* recurse directories in sorted order
* recurse top-level *.dist-info/ directories last
* list filenames in sorted order
* list top-level *.dist-info/RECORD files last

Walk directories in sorted order for reproducibility

---

.github/workflows/test.yml
.travis.yml

Speed-up & extend testing by moving aarch64 from Travis CI to GitHub Actions.

ci: run aarch64 tests on GitHub Actions

---

tests/integration/internal_rpath/setup.py
tests/integration/multiple_top_level/setup.py
tests/integration/nonpy_rpath/setup.py
tests/integration/test_manylinux.py

This should ease a bit writing new integration tests.
The logic to build command lines has been moved in helpers so that tests are not clobbered with multiple lines just for that but instead focus on what's being tested.

chore: refactor test_manylinux

---

.github/workflows/test.yml
tests/integration/test_manylinux.py
tests/integration/testdependencies/dependency.c
tests/integration/testdependencies/testdependencies.c

Add some `armv7l` & `i686` tests on GHA.
QEMU `ppc64le` & `s390x` have been tested but are disabled here as Travis CI can do the job natively for now.
Related to #550, QEMU testing goes over the time limit on GHA when testing with all manylinux images.
I tried pytest-xdist, [automatically grouping](https://github.com/pytest-dev/pytest-xdist/issues/58#issuecomment-1985498074) integration tests by image but that did not help with timings for some reason (& the tests aren't ready for such parallelization as they access the shared filesystem R/W when building some tests).

ci: run more integration tests on GitHub Actions

---

src/auditwheel/main_repair.py
src/auditwheel/repair.py
src/auditwheel/tools.py
src/auditwheel/wheeltools.py
tests/integration/test_bundled_wheels.py
tests/unit/test_tools.py

Add `--zip-compression-level` and `AUDITWHEEL_ZIP_COMPRESSION_LEVEL` env to specify zip compression level.
This PR do not change the default level.
Part of #545.
As in https://github.com/pypa/auditwheel/pull/545#issuecomment-2676697741, we don't want to alter the default compress level. However I do want to add this argument to have the ability to change it.
I'm not very sure about the best place to add test for this.

feat: add option to set zip compression level

---

src/auditwheel/elfutils.py
src/auditwheel/policy/__init__.py
src/auditwheel/repair.py
src/auditwheel/tools.py
tests/unit/test_tools.py

regression introduced in #480
fix #557

fix: is_subdir to return True when path == root

---

src/auditwheel/tools.py
tests/integration/test_bundled_wheels.py

zip timestamps do not use POSIX timestamp, they use DOS timestamps that starts   on 1980-01-01.
fix #566

fix: clip zip timestamp to 1980-01-01

---

src/auditwheel/lddtree.py
src/auditwheel/policy/__init__.py
tests/unit/test_policy.py

This order was changed and not unreliable since it's using an unordered set in 6.3.0

fix: respect `DT_NEEDED` entries order in `lddtree`

---

src/auditwheel/policy/manylinux-policy.json

libanl was addedd to resolv in glibc 2.2.5 in 2001 to support async
dns queries.
It uses private GLIBC symbols, thus to ensure it works with higher
glibc runtime versions, it must be shared linked and should not be
vendored into the wheels. (similar to libdl / dlopen)
In 2021 with glibc 2.34 similar to many other split libraries, libanl
got folded into libc itself, and thus any applications that use async
dns queries no longer gain libanl NEEDED shared library dependency
with a stub remaining in place. (similar to libdl / libpthread etc).
Thus for policies between 2.2.5 and 2.33 there is a need to allow list
libanl, for example when vendoring modern builds of icu.
Longer term, it would be interested to support dropping libraries,
because policies built to manylinux 2.34 policy really …

manylinux-policy: allow glibc component libanl
